version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: yousef:lates
    container_name: app
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./app:/app